[font]
size = 18.0

#SF Mono (old font)

[font.bold]
family = "Iosevka Custom"
style = "Bold"

[font.bold_italic]
family = "Iosevka Custom"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka Custom"
style = "Italic"

[font.normal]
family = "Iosevka Custom"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
opacity = 0.85

[cursor]
	blink_interval = 500
	blink_timeout = 0
	[cursor.style]
		shape = "Block"
		blinking = "Always"
